### ISSUE TITLE
The Truth Detective (pre release available 16th March 2023) 

### ISSUE THREAD

**Issue by AbiSmi99** [alphagov/data-ethics-and-society-reading-group#24]
Tim Harford (of the BBC podcast more or less fame) is a genius at communicating stories with data.  This book is aimed at 9-12 year olds,  
https://www.amazon.co.uk/Truth-Detective-sense-world-numbers/dp/1526364573/ref=sr_1_3?crid=3SKSCC1HI40YO&keywords=tim+harford&qid=1677663386&sprefix=tim+harfor%2Caps%2C287&sr=8-3

Bringing things back to basics is often something that's hard for analysts.   Often the analysis is complex and for those trained to communicate in an academic environment, it can be hard to communicate in an accessible way.

**Comment by mshodge** [comment]
Thanks Abi, will add now.
